# Telegram Bot Token
telegram.bot.token=${BOT_TOKEN}

# Database Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db
spring.datasource.username=student
spring.datasource.password=${DB_PASSWORD}

# OpenWeatherMap API Key
weather.api.key=${OWM_API_KEY}

spring.jpa.hibernate.ddl-auto=update
logging.level.pro.sky.telegrambot=DEBUG

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect