# Telegram Bot Token
telegram.bot.token=8398268958:AAGMpGgQ11rpm8L_FD0IWjXkc5YEMjMcHpM

# Database Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db
spring.datasource.username=student
# postgres
spring.datasource.password=${PassBD}
#spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=update

# Optional: Logging level for debugging
logging.level.pro.sky.telegrambot=DEBUG